name: ISPConfig mirror

on:
  # Mirror every midnight
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror official git repository to github
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://git.ispconfig.org/ispconfig/ispconfig3.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "TLii/ISPconfig3"
          destination_branch: "refs/heads/*"
          destination_ssh_private_key: ${{ secrets.ISPCONFIG_DESTINATION_DEPLOY_KEY }}
